@{
    RootModule        = 'PSInsightHTML.psm1'
    ModuleVersion     = '0.10.0'
    GUID              = 'E3B5F39D-8C4F-45E0-8F10-BAEF3F36B86A'
    Author            = 'PSInsightHTML'
    CompanyName       = 'PSInsightHTML'
    Copyright         = 'Copyright (c) PSInsightHTML'
    Description       = 'Enterprise PowerShell HTML reporting framework.'
    PowerShellVersion = '5.1'
    FunctionsToExport = @(
        'New-PSIReport'
        'New-PSIAssessment'
        'Add-PSIAssessment'
        'Get-PSIFindingSummary'
        'Get-PSIAssessmentSummary'
        'Get-PSIReportSummary'
        'Add-PSIReportOverview'
        'Add-PSISection'
        'Add-PSIRow'
        'Add-PSIKPI'
        'Add-PSIKeyValue'
        'Add-PSIInsight'
        'Add-PSIStatus'
        'Add-PSIFilter'
        'New-PSICondition'
        'New-PSIFinding'
        'Add-PSIFinding'
        'Add-PSIAlert'
        'Add-PSIRecommendation'
        'Add-PSITable'
        'Add-PSIChart'
        'Add-PSIText'
        'Export-PSIReport'
        'Get-PSIReportCatalog'
        'New-PSIADUserInventory'
        'New-PSIADGroupPolicyAssessment'
        'New-PSIADGroupAssessment'
        'New-PSIADReplicationAssessment'
        'New-PSIADDNSAssessment'
        'New-PSIADSitesSubnetsAssessment'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}
